project_out:
  type: object
  properties:
    id:
      $ref: './id.yaml#/id_string'
    org_id:
      $ref: ./org_id.yaml
    created_at:
      $ref: ./created_at.yaml
    updated_at:
      $ref: ./updated_at.yaml
    name:
      type: string
      maxLength: 255
      description: Represents the name of the project.
      example: Fast and Furious
    sub_project:
      type: string
      nullable: true
      maxLength: 255
      description: Represents the name of the sub_project.
      example: Formula One
    display_name:
      type: string
      maxLength: 513
      description: |
        This is a combination of name and sub_project separated by a / and spaces.
        In case if no sub_project is present it is same as name of the project.
      example: Fast and Furious / Formula One
    code:
      type: string
      maxLength: 255
      description: |
        This represents the code of project.
      example: FF-032
    description:
      type: string
      nullable: true
      maxLength: 255
      description: |
        This represents the description of project.
      example: Win the trophy
    is_enabled:
      type: boolean
      description: |
        This indicates if the project is enabled for use within the organisation.
      default: true
      example: true
    category_ids:
      type: array
      description: |
        Has the list of all category ids that are applicable for this project.
      items:
        type: integer

project_in:
  type: object
  properties:
    id:
      $ref: './id.yaml#/id_string'
    org_id:
      $ref: ./org_id.yaml
    created_at:
      $ref: ./created_at.yaml
    updated_at:
      $ref: ./updated_at.yaml
    name:
      type: string
      maxLength: 255
      description: Represents the name of the project.
      example: Fast and Furious
    sub_project:
      type: string
      maxLength: 255
      description: Represents the name of the sub_project.
      example: Formula One
    display_name:
      type: string
      maxLength: 513
      description: |
        This is a combination of name and sub_project separated by a / and spaces.
        In case if no sub_project is present it is same as name of the project.
      example: Fast and Furious / Formula One
    code:
      type: string
      maxLength: 255
      description: |
        This represents the code of project.
      example: FF-032
    description:
      type: string
      maxLength: 255
      description: |
        This represents the description of project.
      example: Win the trophy
    is_enabled:
      type: boolean
      description: |
        This indicates if the project is enabled for use within the organisation.
      default: true
      example: true
    category_ids:
      type: array
      description: |
        Has the list of all category ids that are applicable for this project.
      items:
        type: int
        example: 16570
