openapi: 3.0.3
info:
  version: '3.0'
  title: Common APIs
  contact:
    name: Integrations
    email: support@fylehq.com
servers:
  - url: 'https://accounts.fylehq.com'
    description: Live Server
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://accounts.fylehq.com/app/developers/#/oauth/authorize'
          tokenUrl: 'https://accounts.fylehq.com/oauth/token'
          scopes:
            common.*: Grant all COMMON actions
tags:
  - name: Places
    description: |
      These APIs gives the places suggestions and geographic data of a place.
  - name: Data Extraction
    description: |
      These APIs gives the expense relevant data from the reciepts
paths:
  /common/places:
    $ref: paths/common@places.yaml
  '/common/places/{id}':
    $ref: 'paths/common@places@{id}.yaml'
  /common/expense_extract:
    $ref: paths/common@expense_extract.yaml
